=== edwardkort/WWIDesigner/WWIDesigner/src/main/com/wwidesigner/geometry/bind/Instrument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wii="http://www.wwidesigner.com/Instrument" targetNamespace="http://www.wwidesigner.com/Instrument"
	elementFormDefault="unqualified">

	<xsd:element name="instrument" type="wii:Instrument" />

	<xsd:complexType name="Instrument">
		<xsd:annotation>
			<xsd:documentation>The physical geometry of a wood wind. Dimensions
				may represent initial values subject to optimization or final values
				fixed throughout the calculations.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="lengthType" type="wii:LengthType">
				<xsd:annotation>
					<xsd:documentation>Units of measurement, applied to all dimensions.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="mouthpiece" type="wii:Mouthpiece"
				minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Description of the "drive" end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="borePoint" type="wii:BorePoint"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Sequence of inside diameter measurements for
						non-uniform bore, from fipple, cork or other head-end termination,
						to bottom-end. Assume segments between bore points
						are conical,
						with linear increase in diameter.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="hole" type="wii:Hole" minOccurs="0"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Hole specifications for toneholes,
						from
						mouthpiece to bottom-end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="termination" type="wii:Termination">
				<xsd:annotation>
					<xsd:documentation>Description of bottom end. The position and bore
						diameter of the termination is specified by the borePoint with the
						greatest position.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="LengthType">
		<xsd:annotation>
			<xsd:documentation>An enumeration, applied globally to all
				Dimensions, indicating mm or inch values.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="mm" />
			<xsd:enumeration value="in" />
			<xsd:enumeration value="m" />
			<xsd:enumeration value="cm" />
			<xsd:enumeration value="ft" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Dimension">
		<xsd:annotation>
			<xsd:documentation>Base class for a dimensional double value.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:double" />
	</xsd:simpleType>

	<xsd:simpleType name="ZeroOrMore">
		<xsd:annotation>
			<xsd:documentation>A non-negative Dimension.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="wii:Dimension">
			<xsd:minInclusive value="0" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="MoreThanZero">
		<xsd:annotation>
			<xsd:documentation>A Dimension with a value greater than 0.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="wii:Dimension">
			<xsd:minExclusive value="0" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="BorePoint">
		<xsd:annotation>
			<xsd:documentation>Represents a bore position and effective diameter,
				measured from an arbitrary position, greater positions toward the
				foot of the instrument. Diameters between borePoints are linearly
				interpolated. This list includes borePoints above and below the
				mouthpiece position.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="borePosition" type="wii:Dimension" />
			<xsd:element name="boreDiameter" type="wii:ZeroOrMore" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Key">
		<xsd:annotation>
			<xsd:documentation>Representation of a key mechanism over a tone
				hole.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="diameter" type="wii:MoreThanZero" />
			<xsd:element name="holeDiameter" type="wii:ZeroOrMore" />
			<xsd:element name="height" type="wii:ZeroOrMore" />
			<xsd:element name="thickness" type="wii:ZeroOrMore" />
			<xsd:element name="wallThickness" type="wii:ZeroOrMore" />
			<xsd:element name="chimneyHeight" type="wii:ZeroOrMore" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Hole">
		<xsd:annotation>
			<xsd:documentation>A tone hole with optional key mechanism. The tone
				hole assumes a cylindrical shape with a radiused inner edge. More
				complexity is possible, including truncated conical profiles and
				angled holes.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="0" />
			<xsd:element name="borePosition" type="wii:Dimension">
				<xsd:annotation>
					<xsd:documentation>Position of hole, relative to reference
						position, measured from mouthpiece to bottom end.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="diameter" type="wii:MoreThanZero" />
			<xsd:element name="height" type="wii:MoreThanZero" />
			<xsd:element name="innerCurvatureRadius" type="wii:ZeroOrMore"
				minOccurs="0" />
			<xsd:element name="key" type="wii:Key" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Mouthpiece">
		<xsd:annotation>
			<xsd:documentation>The sound-generation element. Represents a choice between
				possible sound-generation mechanisms: flute, fipple flute, cane reed,
				or lip reed (brass).
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="position" type="wii:Dimension">
				<xsd:annotation>
					<xsd:documentation>The position of the mouthpiece: center of
						embouchure hole, splitting edge, etc. as appropriate for the
						mouthpiece type.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice>
				<xsd:element name="embouchureHole">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="length" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Embouchure hole length (size in longtitudinal direction).
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="width" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Embouchure hole width (size in transverse direction, direction of air stream).
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="height" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Chimney height of hole, from inside to outside.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="airstreamLength" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Length of air stream from player's lips to edge of embouchure hole.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="airstreamHeight" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Height of air stream from player's lips.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="fipple">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="windowLength" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Distance from fipple to sound blade.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windowWidth" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Side-to-side width of window.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="fippleFactor" type="wii:MoreThanZero"
								minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>An empirical multiplier of the calculated
										characteristic dimension of the window.
										The impedance model
										does not use this value.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windowHeight" type="wii:MoreThanZero"
								minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Average "height" of window, between inside
										and outside of tube.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windwayLength" type="wii:MoreThanZero"
								minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Length of windway, from beak to exit.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="windwayHeight" type="wii:MoreThanZero"
								minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Average height of windway at the exit.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="singleReed">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="alpha" type="xsd:double">
								<xsd:annotation>
									<xsd:documentation>Coefficient of frequency in adjustment to
										normalized admittance, in milliseconds.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="doubleReed">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="alpha" type="xsd:double">
								<xsd:annotation>
									<xsd:documentation>Coefficient of frequency in adjustment to
										normalized admittance, in milliseconds.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="crowFreq" type="wii:MoreThanZero">
								<xsd:annotation>
									<xsd:documentation>Frequency of reed crow. (Place-holder.)
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="lipReed">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="alpha" type="xsd:double">
								<xsd:annotation>
									<xsd:documentation>Coefficient of frequency in adjustment to
										normalized admittance, in milliseconds.
									</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:element name="beta" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>For flow-node mouthpieces, jet spatial amplification factor,
						dimensionless value typically between 0.3 and 0.4.
						See Auvray, et al., "Regime change and oscillation
						thresholds in recorder-like instruments",
						J. Acoust. Soc. Am. 131 (2), February 2012.
						For pressure-node mouthpieces, dimensionless adjustment to normalized admittance.
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:double">
						<xsd:minInclusive value="-1"></xsd:minInclusive>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Termination">
		<xsd:annotation>
			<xsd:documentation>Description of the opening at the bottom end of
				the instrument.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="flangeDiameter" type="wii:ZeroOrMore">
				<xsd:annotation>
					<xsd:documentation>Outer diameter of the open end.
						Zero if the
						bottom end is closed.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== edwardkort/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/optimization/example/1HoleNAF1.xml
<?xml version="1.0" encoding="UTF-8"?>
<wii:instrument xmlns:wii="http://www.wwidesigner.com/Instrument"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../../../../../main/com/wwidesigner/geometry/bind/Instrument.xsd ">
	<name>1 hole NAF1</name>
	<description>Straight bore NAF with 1 hole</description>
	<lengthType>in</lengthType>
	<mouthpiece>
		<position>0.20</position>
		<fipple>
			<windowLength>0.17</windowLength>
			<windowWidth>0.68</windowWidth>
			<fippleFactor>0.615</fippleFactor>
			<windowHeight>0.35</windowHeight>
			<windwayHeight>0.031</windwayHeight>
		</fipple>
		<beta>0.3</beta>
	</mouthpiece>
	<borePoint>
		<borePosition>0</borePosition>
		<boreDiameter>1.028</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>11.97</borePosition>
		<boreDiameter>1.041</boreDiameter>
	</borePoint>
	<hole>
		<borePosition>8.1</borePosition>
		<diameter>0.398</diameter>
		<height>0.165</height>
	</hole>
	<termination>
		<flangeDiameter>1.541</flangeDiameter>
	</termination>
</wii:instrument>

=== edwardkort/WWIDesigner/WWIDesigner/src/test/com/wwidesigner/geometry/bind/example/D_NAF.xml
<?xml version="1.0" encoding="utf-8"?>
<wii:instrument xmlns:wii="http://www.wwidesigner.com/Instrument"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wwidesigner.com/Instrument ../Instrument.xsd ">
	<name>D NAF</name>
	<description>7-hole NAF, key of D, A=432</description>
	<lengthType>in</lengthType>
	<mouthpiece>
		<position>0</position>
		<fipple>
			<windowLength>0.15</windowLength>
			<windowWidth>0.64</windowWidth>
			<fippleFactor>0.91</fippleFactor>
			<windowHeight>0.20</windowHeight>
			<windwayLength>1.50</windwayLength>
			<windwayHeight>0.031</windwayHeight>
		</fipple>
	</mouthpiece>
	<borePoint>
		<borePosition>0</borePosition>
		<boreDiameter>1.16</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>9.8</borePosition>
		<boreDiameter>1.16</boreDiameter>
	</borePoint>
	<borePoint>
		<borePosition>13.3</borePosition>
		<boreDiameter>1.06</boreDiameter>
	</borePoint>
	<hole>
		<name>7</name>
		<borePosition>5.6</borePosition>
		<diameter>0.284</diameter>
		<height>0.18</height>
		<innerCurvatureRadius>0.02</innerCurvatureRadius>
	</hole>
	<hole>
		<name>6</name>
		<borePosition>6.85</borePosition>
		<diameter>0.328</diameter>
		<height>0.18</height>
		<innerCurvatureRadius>0.02</innerCurvatureRadius>
	</hole>
	<hole>
		<name>5</name>
		<borePosition>8.1</borePosition>
		<diameter>0.312</diameter>
		<height>0.18</height>
		<innerCurvatureRadius>0.02</innerCurvatureRadius>
	</hole>
	<hole>
		<name>4</name>
		<borePosition>10.3</borePosition>
		<diameter>0.403</diameter>
		<height>0.18</height>
		<innerCurvatureRadius>0.02</innerCurvatureRadius>
	</hole>
	<hole>
		<name>3</name>
		<borePosition>11.55</borePosition>
		<diameter>0.337</diameter>
		<height>0.18</height>
		<innerCurvatureRadius>0.02</innerCurvatureRadius>
	</hole>
	<hole>
		<name>2</name>
		<borePosition>12.75</borePosition>
		<diameter>0.158</diameter>
		<height>0.10</height>
		<innerCurvatureRadius>0.02</innerCurvatureRadius>
	</hole>
	<hole>
		<name>1</name>
		<borePosition>12.80</borePosition>
		<diameter>0.172</diameter>
		<height>0.10</height>
		<innerCurvatureRadius>0.02</innerCurvatureRadius>
	</hole>
	<termination>
		<flangeDiameter>1.44</flangeDiameter>
	</termination>
</wii:instrument>
